---
# @var opatch_gi_conflict_check:description: >
# When calling oracle_opatch for GI, decide if analyze stage of
# opatch/opatchauto should be executed.
# @end
# @var opatch_gi_conflict_check:type: boolean
opatch_gi_conflict_check: "{{ opatch_conflict_check | bool }}"
