:toc:
:toc-placement!:
toc::[]

:sectnums:
:sectnumlevels: 4

== Overview

IMPORTANT: This documentation is a short description to install all needed tools for ansible-oracle on a Windows based hostsystem. +
Please read further notes for more informations.

:puml: http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/Rendanic/ansible-oracle/tbrdoc/doc

image::{puml}/chocolatey.puml[Vagrant]

* Requirements
** Intel/AMD x86 CPU is mandatory +
no support for Mac with M1
** 16 GB RAM
** 150 GB free Disk space +
The free space is needed in your home directory in Windows.
** Admin priviledges on Host machine
** Hyper-V disabled
** no WSL/WSL2 for installation +
You could try it by your own, but the documentation expect that Hyper-V is completly disabled and no WSL/WSL2 is used.

WARNING: There are a lot issues wehn Hyper-V is active on host machine. +
Please switch Hyper-V completly off, before starting the boxes with Vagrant. +
Really working solutions with Vagrant + VirtualBox and Hyper-V are welcome.

== Installation

=== Disable Hyper-V in Windows

WARNING: There are numerous problems with Vagrant & VirtualBox when Hyper-V is enabled. +
It could work, but it is recommended to disable it for `ansible-oracle`.

IMPORTANT: All commands require a cmd.exe with admin rights.

.Check setting of Hyper-V
----
bcdedit
----

The output should contain a line with `hypervisorlaunchtype`. +
If the line is not shown or `Off`, Hyper-V is completly disabled.

.Output
[quote,output from bcdedit]
----
# bcdedit

Windows-Start-Manager
---------------------
...

Windows-Startladeprogramm
-------------------------
...
hypervisorlaunchtype    Off
----

If it is `Auto` or `On`

.Disable Hyper-V with immediate reboot
----
bcdedit /set {current} hypervisorlaunchtype off
shutdown -r -t 0
----


=== Chocolatey

IMPORTANT: The installation of Chocolatey is not mandatory for `ansible-oracle`. +
All tools could be installed manually. Make sure, that all are executable from `git+bash`. +
*It is highly recommended to use Chocolatey with `ansible-oracle`.*

IMPORTANT: See the link:https://chocolatey.org/install[Homepage of chocolatey] for more details.

.Execute in PowerShell with Admin rights
----
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
----

=== git+bash, VirutalBox and Vagrant

.Execute in cmd.exe with admin rights
----
choco install git vagrant virtualbox
----

=== ConEmu - Handy Windows Terminal

IMPORTANT: This step is optional.

This is a really good alternative terminal to `cmd.exe` for windows. +
It is not recommended for `ansible-oracle` but you should give it a try and enfoy it - especially when VSCode is not used.

link:https://conemu.github.io[Homepage of ConEmu]

.Execute in cmd.exe with admin rights
----
choco install conemu
----

=== Visual Studio Code

IMPORTANT: This step is optional. +
You should use VSCode - especially when _Advanced_ or _Expert_ setups are planned for a later time.

link:https://code.visualstudio.com:[Homepage for Visual Studio Code]

.Execute in cmd.exe with admin rights
----
choco install vscode.install
----

== Configuration

=== SSH-Setup

WARNING: The example expects the private key at the default location.

IMPORTANT: Create a custom key and place the public key in same directory as the Vagrantfile.
Do _not_ use the created keys from Vagrant. +
You should _always_ use the `ssh-agent` to connect to all machines.

IMPORTANT: All commands are executed in `git+bash` on the Host machine - _not_ inside a VM!

.Create a key when needed
----
ssh-keygen
----

.Output
[quote, output of ssh-keygen]
----
ssh-keygen

Generating public/private rsa key pair.

Enter file in which to save the key (/c/Users/User/.ssh/id_rsa): Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /c/Users/User/.ssh/id_rsa
Your public key has been saved in /c/Users/User/.ssh/id_rsa.pub
The key fingerprint is:
SHA256:Xq9EGKMUEXFkxeli4NilfvwEkOAmvkV1PiRteA+NQRQ ubuntu@ansible-oracle-bastion
----

IMPORTANT: Enable Agent Forwarding for all SSH-Sessions. +
This is *mandatory* for Visual Studio Code.

.Enable Agent Forwarding for all SSH-Sessions.
----
code ~/.ssh/config

Host *
  ForwardAgent yes
----

.Start a ssh-agent (bash)
----
eval $(ssh-agent)
----

.Output
[quote, output of ssh-keygen]
----
eval $(ssh-agent)
Agent pid 16840
----

.Import a key
----
ssh-add ~/.ssh/id_rsa
----

.Output
[quote, output of ssh-keygen]
----
$ ssh-add ~/.ssh/id_rsa
Identity added: /c/Users/User/.ssh/id_rsa (User@unknown)
----

.Show imported keys
----
ssh-add -l
----

.Output
[quote, output of ssh-keygen]
----
ssh-add -l
2048 SHA256:EsVIFzfCLUDTO2cMTf4q4qt2Eu0w1pA2sdcXxh9jyBs User@unknown (RSA)
----

=== Vagrant SSH-Setup

IMPORTANT: The Vagrantfile has a provisioner script block which copy a stored `id_rsa.pub` into `authorized_keys` on the target machine.

The exact command to copy the key is shown during the deployment description.

=== Vagrant Plugins

The following modules are used by the tutorial examples.

* install* vagrant-disksize +
This is an experimental plugin which is needed to resize the 1. disk of a vagrant box. +
----
vagrant plugin install vagrant-disksize
----
