---
# @var mos_login:description: Login name for My Oracle Support (required)
# @var mos_password:description: Password for My Oracle Support (required)

# @var oracle_plat_lang:description: >
# This is an internal variable for downloading patches.
# Usually no need to change it.
# @end
oracle_plat_lang: 226P  # Linux x86-64

# @var opatchinfo:description: >
# This is an internal variable for downloading patches.
# Usually no need to change it.
# @end
opatchinfo: []

# @var oracle_patch_download_dir:description: Target directory for patch downloads
oracle_patch_download_dir: "{{ oracle_sw_source_local }}"

# @var oracle_patch_download_host:description: `delegate_to` host for downloads
oracle_patch_download_host: "localhost"
